import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Onest } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest", // esto te permite usarla como variable CSS
});

export const metadata: Metadata = {
  title: "Portfolio - Liuber Fornaris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`antialiased max-w-2xl m-auto ${onest.variable}`}>
        {" "}
        <Header />
        {children}
      </body>
    </html>
  );
}
